import { CraftItem } from './types';

export const CRAFT_ITEMS: CraftItem[] = [
  {
    id: 1,
    name: 'Rainbow Owl',
    description: 'A wise old owl bursting with every color of the rainbow. Knows all the best bedtime stories.',
    price: 350.00,
    imageUrl: 'https://i.ibb.co/311W9K9/owl.jpg',
    category: 'Crochet',
  },
  {
    id: 2,
    name: 'Barnaby the Beagle',
    description: 'A loyal and playful beagle pup with floppy ears and a heart of gold. Expert at sniffing out snacks.',
    price: 320.00,
    imageUrl: 'https://i.ibb.co/g3GkQYv/dog.jpg',
    category: 'Crochet',
  },
  {
    id: 3,
    name: 'Sad Dino-Cat',
    description: 'A fierce but friendly dino-cat, always ready for a prehistoric cuddle. Just needs a little love.',
    price: 280.00,
    imageUrl: 'https://i.ibb.co/6P2T8c1/dino.jpg',
    category: 'Crochet',
  },
  {
    id: 4,
    name: 'Dapper Rabbit',
    description: 'A charming rabbit with a stylish bow-tie and suspenders. Ready for any formal occasion.',
    price: 380.00,
    imageUrl: 'https://i.ibb.co/Wc2c77V/bunny.jpg',
    category: 'Crochet',
  },
  {
    id: 5,
    name: 'Classic Teddy Bear',
    description: 'A timeless, huggable friend with a sweet smile. Perfect for cuddles and adventures.',
    price: 400.00,
    imageUrl: 'https://i.ibb.co/hZ2vPqk/brown-bear.jpg',
    category: 'Crochet',
  },
  {
    id: 6,
    name: 'Bear in Overalls',
    description: 'This little bear is dressed for a day of fun in his stylish red and white striped overalls.',
    price: 450.00,
    imageUrl: 'https://i.ibb.co/dKqS1p5/bear-in-overalls.jpg',
    category: 'Crochet',
  },
  {
    id: 7,
    name: 'Pink Patchwork Pup',
    description: 'A sweet puppy in shades of pink with adorable paw-print feet. A truly unique companion.',
    price: 360.00,
    imageUrl: 'https://i.ibb.co/yQJ4G2K/pink-dog.jpg',
    category: 'Crochet',
  },
  {
    id: 8,
    name: 'Ferdinand the Frog',
    description: 'With his long legs and big eyes, Ferdinand is always ready to leap into a new adventure.',
    price: 300.00,
    imageUrl: 'https://i.ibb.co/w7z6t2p/green-frog.jpg',
    category: 'Crochet',
  },
  {
    id: 9,
    name: 'Elephant Lovey',
    description: 'A comforting companion for your little one, combining a soft blanket with a gentle elephant friend.',
    price: 420.00,
    imageUrl: 'https://i.ibb.co/Yd4NnB2/elephant-lovey.jpg',
    category: 'Crochet',
  },
  {
    id: 10,
    name: 'Granny Square Cardigan',
    description: 'A vibrant, retro-style cardigan made from colorful granny squares. A cozy and stylish statement piece.',
    price: 850.00,
    imageUrl: 'https://i.ibb.co/zZf4d88/granny-square-cardigan.jpg',
    category: 'Crochet',
  },
  {
    id: 11,
    name: 'Flower Garden Blanket',
    description: 'Bring a field of flowers indoors with this beautiful blanket, featuring colorful crochet blossoms.',
    price: 950.00,
    imageUrl: 'https://i.ibb.co/L9s3J7V/flower-blanket.jpg',
    category: 'Crochet',
  },
  {
    id: 12,
    name: 'Rainbow C2C Blanket',
    description: 'A bright and cheerful corner-to-corner blanket with a stunning rainbow gradient.',
    price: 900.00,
    imageUrl: 'https://i.ibb.co/M7XFq4n/rainbow-c2c-blanket.jpg',
    category: 'Crochet',
  },
  {
    id: 13,
    name: 'Ocean Waves Blanket',
    description: 'Soothing waves of blue, grey, and white make this blanket a calming and beautiful addition to any room.',
    price: 980.00,
    imageUrl: 'https://i.ibb.co/D8G32v2/wave-blanket.jpg',
    category: 'Crochet',
  },
  {
    id: 14,
    name: 'Christmas Gnome',
    description: 'A festive little gnome with a big grey hat, ready to bring some holiday cheer to your home.',
    price: 250.00,
    imageUrl: 'https://i.ibb.co/x7GqJ3Q/gnome.jpg',
    category: 'Crochet',
  },
  {
    id: 15,
    name: 'Pebble Art Cat',
    description: 'A stylized cat silhouette meticulously crafted from colorful pebbles. A unique piece for any cat lover.',
    price: 450.00,
    imageUrl: 'https://i.ibb.co/MfZ0x6w/mosaic-cat-2.jpg',
    category: 'Decor',
  },
  {
    id: 16,
    name: 'Money Tree Sculpture',
    description: 'This mixed-media tree features a trunk of bark and leaves made of coins. A symbol of prosperity and creativity.',
    price: 550.00,
    imageUrl: 'https://i.ibb.co/VMy4SjQ/coin-tree.jpg',
    category: 'Decor',
  },
  {
    id: 17,
    name: 'Rustic Cross Wall Art',
    description: 'A textured piece of art featuring a simple wooden cross against a dark, metallic-flecked background.',
    price: 480.00,
    imageUrl: 'https://i.ibb.co/jLD3XkP/wood-cross.jpg',
    category: 'Decor',
  },
  {
    id: 18,
    name: 'Musical Memories Tray',
    description: 'A beautiful decoupage tray adorned with sheet music, instruments, and cherished photos. A truly personal piece.',
    price: 600.00,
    imageUrl: 'https://i.ibb.co/bF9hS6S/decoupage-tray.jpg',
    category: 'Decor',
  },
  {
    id: 19,
    name: 'Owl Army',
    description: 'A parliament of multi-colored owls, ready to brighten up any shelf or desk. Price is per owl.',
    price: 150.00,
    imageUrl: 'https://i.ibb.co/L8P4Fgg/owl-army.jpg',
    category: 'Crochet',
  },
  {
    id: 20,
    name: 'Purple & Yellow Friend',
    description: 'A quirky and cute creature in bold purple and yellow. What is it? That\'s for you to decide!',
    price: 220.00,
    imageUrl: 'https://i.ibb.co/Xz9wK7J/purple-yellow-monster.jpg',
    category: 'Random',
  },
];
